# Based on the issue template
name: Feature request
description: Suggest an idea for this project
title: "[FEAT] <title>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
# This image is deprecated. We will not offer support for this image and it will not be updated.

Jackett has a bot publishing nightly stable releases
Please switch to latest tag for stable

