#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "${AUTO_UPDATE,,}" == "true" ]] && [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    COMMAND="/app/Jackett/jackett_launcher.sh"
else
    COMMAND="/app/Jackett/jackett --NoUpdates"
fi


if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9117" \
            s6-setuidgid abc ${COMMAND} ${RUN_OPTS}
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9117" \
            ${COMMAND} ${RUN_OPTS}
fi
