#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${AUTO_UPDATE+x} ]] || [[ "${AUTO_UPDATE}" == "true" ]]; then
    COMMAND="/app/Jackett/jackett_launcher.sh"
else
    COMMAND="/app/Jackett/jackett --NoUpdates"
fi


exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 9117" \
        s6-setuidgid abc ${COMMAND} ${RUN_OPTS}
